const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Shirt",
      slug: "adidas-fit-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      countInStock: 20,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pants",
      slug: "nike-slim-pants",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 25,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pants",
      slug: "adidas-fit-pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 65,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      countInStock: 20,
      description: "high quality product",
    },
  ],
};

export default data;
